micronaut.application.name=micronaut-user-app-api

datasources.default.db-type=mysql
datasources.default.dialect=MYSQL
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.url=jdbc:mysql://localhost:3306/usersdb?allowPublicKeyRetrieval=true&useSSL=false
datasources.default.username=usersdb_user
datasources.default.password=password

jpa.default.entity-scan.packages=com.users.entity
jpa.default.properties.hibernate.hbm2ddl.auto=none

flyway.datasources.default.enabled=true
flyway.datasources.default.baseline-on-migrate=true

micronaut.security.authentication=bearer
micronaut.security.token.jwt.signatures.secret.generator.secret=MyVerySecretJWTKeyForMicronautApplication2026
micronaut.security.enabled=true
micronaut.security.intercept-url-map[0].pattern=/auth/**
micronaut.security.intercept-url-map[0].access[0]=isAnonymous()
micronaut.security.intercept-url-map[1].pattern=/api/users/**
micronaut.security.intercept-url-map[1].access[0]=isAuthenticated()

redis.uri=redis://localhost:6379