# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/usersdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=usersdb_user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.expiration=900000

# Logging
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace