import { User } from "../../users/models/user";

export const USERS_MOCK_LIST: User[] = [
    {
      id: 1,
      name: 'Carlos',
      lastName: 'Ramírez',
      email: 'carlos.ramirez@email.com',
      username: 'cramirez',
      password: '123456',
    },
    {
      id: 2,
      name: 'María',
      lastName: 'González',
      email: 'maria.gonzalez@email.com',
      username: 'mariagonz',
      password: '123456',
    },
    {
      id: 3,
      name: 'Juan',
      lastName: 'Pérez',
      email: 'juan.perez@email.com',
      username: 'juanperz',
      password: '123456',
    },
    {
      id: 4,
      name: 'Ana',
      lastName: 'López',
      email: 'ana.lopez@email.com',
      username: 'analopez',
      password: '123456',
    },
    {
      id: 5,
      name: 'Luis',
      lastName: 'Martínez',
      email: 'luis.martinez@email.com',
      username: 'luismart',
      password: '123456',
    },
    {
      id: 6,
      name: 'Sofía',
      lastName: 'Hernández',
      email: 'sofia.hernandez@email.com',
      username: 'sofiahern',
      password: '123456',
    },
    {
      id: 7,
      name: 'Diego',
      lastName: 'Castro',
      email: 'diego.castro@email.com',
      username: 'diegocastro',
      password: '123456',
    },
    {
      id: 8,
      name: 'Valeria',
      lastName: 'Torres',
      email: 'valeria.torres@email.com',
      username: 'valeriatorres',
      password: '123456',
    },
    {
      id: 9,
      name: 'Andrés',
      lastName: 'Vargas',
      email: 'andres.vargas@email.com',
      username: 'andresvargas',
      password: '123456',
    },
    {
      id: 10,
      name: 'Camila',
      lastName: 'Rojas',
      email: 'camila.rojas@email.com',
      username: 'camilarojas',
      password: '123456',
    },
  ];