import { User } from "../models/user";

export const USERS_MOCK_LIST: User[] = [
    {
      id: 1,
      name: 'Carlos',
      lastName: 'Ramírez',
      email: 'carlos.ramirez@email.com',
      username: 'carlosr',
      password: '123456',
    },
    {
      id: 2,
      name: 'María',
      lastName: 'González',
      email: 'maria.gonzalez@email.com',
      username: 'mariag',
      password: '123456',
    },
    {
      id: 3,
      name: 'Juan',
      lastName: 'Pérez',
      email: 'juan.perez@email.com',
      username: 'juanp',
      password: '123456',
    },
    {
      id: 4,
      name: 'Ana',
      lastName: 'López',
      email: 'ana.lopez@email.com',
      username: 'anal',
      password: '123456',
    },
    {
      id: 5,
      name: 'Luis',
      lastName: 'Martínez',
      email: 'luis.martinez@email.com',
      username: 'luism',
      password: '123456',
    },
    {
      id: 6,
      name: 'Sofía',
      lastName: 'Hernández',
      email: 'sofia.hernandez@email.com',
      username: 'sofiah',
      password: '123456',
    },
    {
      id: 7,
      name: 'Diego',
      lastName: 'Castro',
      email: 'diego.castro@email.com',
      username: 'diegoc',
      password: '123456',
    },
    {
      id: 8,
      name: 'Valeria',
      lastName: 'Torres',
      email: 'valeria.torres@email.com',
      username: 'valeriat',
      password: '123456',
    },
    {
      id: 9,
      name: 'Andrés',
      lastName: 'Vargas',
      email: 'andres.vargas@email.com',
      username: 'andresv',
      password: '123456',
    },
    {
      id: 10,
      name: 'Camila',
      lastName: 'Rojas',
      email: 'camila.rojas@email.com',
      username: 'camilar',
      password: '123456',
    },
  ];